In [1]:
import pandas as pd

df = pd.read_csv("ORIGINAL DATA 1976-2024-presidential-elections.csv")

data source: MIT Election Data and Science Lab, 2017, "U.S. President 1976–2024", https://doi.org/10.7910/DVN/42MVDX, Harvard Dataverse, V10, UNF:6:xpBppxfswpr+u9xZe7/u7w== [fileUNF]

In [2]:
df.columns

Index(['year', 'state', 'state_po', 'state_fips', 'state_cen', 'state_ic',
       'office', 'candidate', 'party_detailed', 'writein', 'candidatevotes',
       'totalvotes', 'version', 'notes', 'party_simplified'],
      dtype='str')

In [3]:
df.shape

(4822, 15)

cut off the old year rows before 2000

In [4]:
df = df.iloc[2411:]

Cut out any rows that are for no Republican or Democrat parties

In [5]:
df = df[df["party_detailed"].str.lower().isin(["republican", "democrat"])]

Lowercase states

In [6]:
df["state"] = df["state"].str.title()

In [7]:
df.head(30)

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party_detailed,writein,candidatevotes,totalvotes,version,notes,party_simplified
2411,2004,Alabama,AL,1,63,41.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,1176394,1883415,20210113,NaN,REPUBLICAN
2412,2004,Alabama,AL,1,63,41.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,693933,1883415,20210113,NaN,DEMOCRAT
2416,2004,Alaska,AK,2,94,81.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,190889,312598,20210113,NaN,REPUBLICAN
2418,2004,Alaska,AK,2,94,81.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,111025,312598,20210113,NaN,DEMOCRAT
2423,2004,Arizona,AZ,4,86,61.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,1104294,2012585,20210113,NaN,REPUBLICAN
2424,2004,Arizona,AZ,4,86,61.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,893524,2012585,20210113,NaN,DEMOCRAT
2427,2004,Arkansas,AR,5,71,42.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,572898,1054945,20210113,NaN,REPUBLICAN
2429,2004,Arkansas,AR,5,71,42.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,469953,1054945,20210113,NaN,DEMOCRAT
2433,2004,California,CA,6,93,71.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,5509826,12421353,20210113,NaN,REPUBLICAN
2435,2004,California,CA,6,93,71.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,6745485,12421353,20210113,NaN,DEMOCRAT
2443,2004,Colorado,CO,8,84,62.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,1101255,2129630,20210113,NaN,REPUBLICAN
2447,2004,Colorado,CO,8,84,62.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,1001732,2129630,20210113,NaN,DEMOCRAT
2452,2004,Connecticut,CT,9,16,1.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,693826,1578769,20210113,NaN,REPUBLICAN
2455,2004,Connecticut,CT,9,16,1.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,857488,1578769,20210113,NaN,DEMOCRAT
2460,2004,Delaware,DE,10,51,11.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,171660,375190,20210113,NaN,REPUBLICAN
2462,2004,Delaware,DE,10,51,11.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,200152,375190,20210113,NaN,DEMOCRAT
2466,2004,District Of Columbia,DC,11,53,55.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,21256,227586,20210113,NaN,REPUBLICAN
2469,2004,District Of Columbia,DC,11,53,55.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,202970,227586,20210113,NaN,DEMOCRAT
2474,2004,Florida,FL,12,59,43.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,3964522,7609810,20210113,NaN,REPUBLICAN
2477,2004,Florida,FL,12,59,43.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,3583544,7609810,20210113,NaN,DEMOCRAT
2481,2004,Georgia,GA,13,58,44.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,1914254,3301875,20210113,NaN,REPUBLICAN
2482,2004,Georgia,GA,13,58,44.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,1366149,3301875,20210113,NaN,DEMOCRAT
2485,2004,Hawaii,HI,15,95,82.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,194191,429013,20210113,NaN,REPUBLICAN
2487,2004,Hawaii,HI,15,95,82.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,231708,429013,20210113,NaN,DEMOCRAT
2489,2004,Idaho,ID,16,82,63.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,409235,598376,20210113,NaN,REPUBLICAN
2490,2004,Idaho,ID,16,82,63.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,181098,598376,20210113,NaN,DEMOCRAT
2494,2004,Illinois,IL,17,33,21.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,2345946,5274322,20210113,NaN,REPUBLICAN
2495,2004,Illinois,IL,17,33,21.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,2891550,5274322,20210113,NaN,DEMOCRAT
2498,2004,Indiana,IN,18,32,22.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,1479438,2468002,20210113,NaN,REPUBLICAN
2499,2004,Indiana,IN,18,32,22.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,969011,2468002,20210113,NaN,DEMOCRAT

Trim some colums we don't need

In [8]:
#see what's in the office column

df['office'].unique()

df = df.drop(columns=['office','writein','notes','party_simplified','version', 'state_fips', 'state_cen', 'state_ic','state_po','candidate'])

Drop DC Columns, and MD and vA

In [9]:
df = df[df["state"] != "District of Columbia"]

df = df[df["state"] != "Maryland"]

df = df[df["state"] != "Virginia"]

Calculate percent to each candidate

In [10]:
df['percent_total_votes'] = df['candidatevotes'] / df['totalvotes']

In [11]:
df.head()

,year,state,party_detailed,candidatevotes,totalvotes,percent_total_votes
2411,2004,Alabama,REPUBLICAN,1176394,1883415,0.624607
2412,2004,Alabama,DEMOCRAT,693933,1883415,0.368444
2416,2004,Alaska,REPUBLICAN,190889,312598,0.610653
2418,2004,Alaska,DEMOCRAT,111025,312598,0.355169
2423,2004,Arizona,REPUBLICAN,1104294,2012585,0.548694

Need to sort this so I only have one line for each state, with whichever party and candidate received the most votes.

In [12]:
df_winners_only = df.loc[
    df.groupby(['year', 'state'])['candidatevotes'].idxmax()
].reset_index(drop=True)

In [13]:
df = df_winners_only

Drop a few more columns and isolate each year to save to add as a column to the census migration data tables for each election year.

In [14]:
df = df.drop(columns=['candidatevotes', 'totalvotes'])

df.head()

   year       state party_detailed  percent_total_votes
0  2004     Alabama     REPUBLICAN             0.624607
1  2004      Alaska     REPUBLICAN             0.610653
2  2004     Arizona     REPUBLICAN             0.548694
3  2004    Arkansas     REPUBLICAN             0.543060
4  2004  California       DEMOCRAT             0.543056

Reorder the columns so state is first

In [17]:
df = df[
    [
        'state',
        'year',
        'party_detailed',
        'percent_total_votes']
]

In [18]:
df_2004_election_winners = df[df["year"] == 2004]
df_2008_election_winners = df[df["year"] == 2008]
df_2012_election_winners = df[df["year"] == 2012]
df_2016_election_winners = df[df["year"] == 2016]
df_2020_election_winners = df[df["year"] == 2020]

In [19]:
df_2004_election_winners

                   state  year party_detailed  percent_total_votes
0                Alabama  2004     REPUBLICAN             0.624607
1                 Alaska  2004     REPUBLICAN             0.610653
2                Arizona  2004     REPUBLICAN             0.548694
3               Arkansas  2004     REPUBLICAN             0.543060
4             California  2004       DEMOCRAT             0.543056
5               Colorado  2004     REPUBLICAN             0.517111
6            Connecticut  2004       DEMOCRAT             0.543137
7               Delaware  2004       DEMOCRAT             0.533468
8   District Of Columbia  2004       DEMOCRAT             0.891839
9                Florida  2004     REPUBLICAN             0.520975
10               Georgia  2004     REPUBLICAN             0.579748
11                Hawaii  2004       DEMOCRAT             0.540096
12                 Idaho  2004     REPUBLICAN             0.683909
13              Illinois  2004       DEMOCRAT             0.548232
14               Indiana  2004     REPUBLICAN             0.599448
15                  Iowa  2004     REPUBLICAN             0.499007
16                Kansas  2004     REPUBLICAN             0.620040
17              Kentucky  2004     REPUBLICAN             0.595495
18             Louisiana  2004     REPUBLICAN             0.567220
19                 Maine  2004       DEMOCRAT             0.535729
20         Massachusetts  2004       DEMOCRAT             0.616167
21              Michigan  2004       DEMOCRAT             0.512307
22             Minnesota  2004     REPUBLICAN             0.476135
23           Mississippi  2004     REPUBLICAN             0.590144
24              Missouri  2004     REPUBLICAN             0.532962
25               Montana  2004     REPUBLICAN             0.590681
26              Nebraska  2004     REPUBLICAN             0.658986
27                Nevada  2004     REPUBLICAN             0.504697
28         New Hampshire  2004       DEMOCRAT             0.502016
29            New Jersey  2004       DEMOCRAT             0.529234
30            New Mexico  2004     REPUBLICAN             0.498384
31              New York  2004       DEMOCRAT             0.561306
32        North Carolina  2004     REPUBLICAN             0.560172
33          North Dakota  2004     REPUBLICAN             0.628613
34                  Ohio  2004     REPUBLICAN             0.508140
35              Oklahoma  2004     REPUBLICAN             0.655704
36                Oregon  2004       DEMOCRAT             0.513487
37          Pennsylvania  2004       DEMOCRAT             0.509238
38          Rhode Island  2004       DEMOCRAT             0.594234
39        South Carolina  2004     REPUBLICAN             0.579819
40          South Dakota  2004     REPUBLICAN             0.599111
41             Tennessee  2004     REPUBLICAN             0.567991
42                 Texas  2004     REPUBLICAN             0.610858
43                  Utah  2004     REPUBLICAN             0.715359
44               Vermont  2004       DEMOCRAT             0.589375
45            Washington  2004       DEMOCRAT             0.528211
46         West Virginia  2004     REPUBLICAN             0.560707
47             Wisconsin  2004       DEMOCRAT             0.496997
48               Wyoming  2004     REPUBLICAN             0.687396

In [ ]:
df_2008_election_winners

In [ ]:
df_2012_election_winners

In [ ]:
df_2016_election_winners

In [ ]:
df_2020_election_winners

Export as csvs

In [20]:
df_2004_election_winners.to_csv('pres-election-results-2004.csv')
df_2008_election_winners.to_csv('pres-election-results-2008.csv')
df_2012_election_winners.to_csv('pres-election-results-2012.csv')
df_2016_election_winners.to_csv('pres-election-results-2016.csv')
df_2020_election_winners.to_csv('pres-election-results-2020.csv')