In [1]:
import pandas as pd

df = pd.read_csv("1976-2024-presidential-elections.csv")

data source: MIT Election Data and Science Lab, 2017, "U.S. President 1976–2024", https://doi.org/10.7910/DVN/42MVDX, Harvard Dataverse, V10, UNF:6:xpBppxfswpr+u9xZe7/u7w== [fileUNF]

In [2]:
df.columns

Index(['year', 'state', 'state_po', 'state_fips', 'state_cen', 'state_ic',
       'office', 'candidate', 'party_detailed', 'writein', 'candidatevotes',
       'totalvotes', 'version', 'notes', 'party_simplified'],
      dtype='str')

In [3]:
df.shape

(4822, 15)

cut off the old year rows before 2000

In [4]:
df = df.iloc[2411:]

Cut out any rows that are for no Republican or Democrat parties

In [5]:
df = df[df["party_detailed"].str.lower().isin(["republican", "democrat"])]

In [6]:
df.head(30)

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party_detailed,writein,candidatevotes,totalvotes,version,notes,party_simplified
2411,2004,ALABAMA,AL,1,63,41.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,1176394,1883415,20210113,NaN,REPUBLICAN
2412,2004,ALABAMA,AL,1,63,41.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,693933,1883415,20210113,NaN,DEMOCRAT
2416,2004,ALASKA,AK,2,94,81.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,190889,312598,20210113,NaN,REPUBLICAN
2418,2004,ALASKA,AK,2,94,81.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,111025,312598,20210113,NaN,DEMOCRAT
2423,2004,ARIZONA,AZ,4,86,61.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,1104294,2012585,20210113,NaN,REPUBLICAN
2424,2004,ARIZONA,AZ,4,86,61.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,893524,2012585,20210113,NaN,DEMOCRAT
2427,2004,ARKANSAS,AR,5,71,42.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,572898,1054945,20210113,NaN,REPUBLICAN
2429,2004,ARKANSAS,AR,5,71,42.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,469953,1054945,20210113,NaN,DEMOCRAT
2433,2004,CALIFORNIA,CA,6,93,71.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,5509826,12421353,20210113,NaN,REPUBLICAN
2435,2004,CALIFORNIA,CA,6,93,71.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,6745485,12421353,20210113,NaN,DEMOCRAT
2443,2004,COLORADO,CO,8,84,62.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,1101255,2129630,20210113,NaN,REPUBLICAN
2447,2004,COLORADO,CO,8,84,62.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,1001732,2129630,20210113,NaN,DEMOCRAT
2452,2004,CONNECTICUT,CT,9,16,1.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,693826,1578769,20210113,NaN,REPUBLICAN
2455,2004,CONNECTICUT,CT,9,16,1.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,857488,1578769,20210113,NaN,DEMOCRAT
2460,2004,DELAWARE,DE,10,51,11.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,171660,375190,20210113,NaN,REPUBLICAN
2462,2004,DELAWARE,DE,10,51,11.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,200152,375190,20210113,NaN,DEMOCRAT
2466,2004,DISTRICT OF COLUMBIA,DC,11,53,55.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,21256,227586,20210113,NaN,REPUBLICAN
2469,2004,DISTRICT OF COLUMBIA,DC,11,53,55.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,202970,227586,20210113,NaN,DEMOCRAT
2474,2004,FLORIDA,FL,12,59,43.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,3964522,7609810,20210113,NaN,REPUBLICAN
2477,2004,FLORIDA,FL,12,59,43.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,3583544,7609810,20210113,NaN,DEMOCRAT
2481,2004,GEORGIA,GA,13,58,44.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,1914254,3301875,20210113,NaN,REPUBLICAN
2482,2004,GEORGIA,GA,13,58,44.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,1366149,3301875,20210113,NaN,DEMOCRAT
2485,2004,HAWAII,HI,15,95,82.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,194191,429013,20210113,NaN,REPUBLICAN
2487,2004,HAWAII,HI,15,95,82.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,231708,429013,20210113,NaN,DEMOCRAT
2489,2004,IDAHO,ID,16,82,63.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,409235,598376,20210113,NaN,REPUBLICAN
2490,2004,IDAHO,ID,16,82,63.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,181098,598376,20210113,NaN,DEMOCRAT
2494,2004,ILLINOIS,IL,17,33,21.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,2345946,5274322,20210113,NaN,REPUBLICAN
2495,2004,ILLINOIS,IL,17,33,21.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,2891550,5274322,20210113,NaN,DEMOCRAT
2498,2004,INDIANA,IN,18,32,22.0,US PRESIDENT,"BUSH, GEORGE W.",REPUBLICAN,False,1479438,2468002,20210113,NaN,REPUBLICAN
2499,2004,INDIANA,IN,18,32,22.0,US PRESIDENT,"KERRY, JOHN",DEMOCRAT,False,969011,2468002,20210113,NaN,DEMOCRAT

Trim some colums we don't need

In [7]:
#see what's in the office column

df['office'].unique()

df = df.drop(columns=['office','writein','notes','party_simplified','version', 'state_fips', 'state_cen', 'state_ic','state_po','candidate'])

Drop DC Columns

In [8]:
df = df[df["state"] != "DISTRICT OF COLUMBIA"]

Calculate percent to each candidate

In [9]:
df['percent_total_votes'] = df['candidatevotes'] / df['totalvotes']

In [10]:
df.head()

,year,state,party_detailed,candidatevotes,totalvotes,percent_total_votes
2411,2004,ALABAMA,REPUBLICAN,1176394,1883415,0.624607
2412,2004,ALABAMA,DEMOCRAT,693933,1883415,0.368444
2416,2004,ALASKA,REPUBLICAN,190889,312598,0.610653
2418,2004,ALASKA,DEMOCRAT,111025,312598,0.355169
2423,2004,ARIZONA,REPUBLICAN,1104294,2012585,0.548694

Need to sort this so I only have one line for each state, with whichever party and candidate received the most votes.

In [11]:
df_winners_only = df.loc[
    df.groupby(['year', 'state'])['candidatevotes'].idxmax()
].reset_index(drop=True)

In [12]:
df = df_winners_only

Drop a few more columns and isolate each year to save to add as a column to the census migration data tables for each election year.

In [14]:
df = df.drop(columns=['candidatevotes', 'totalvotes'])

In [15]:
df_2004_election_winners = df[df["year"] == 2004]
df_2008_election_winners = df[df["year"] == 2008]
df_2012_election_winners = df[df["year"] == 2012]
df_2016_election_winners = df[df["year"] == 2016]
df_2020_election_winners = df[df["year"] == 2020]

In [16]:
df_2004_election_winners

    year           state party_detailed  percent_total_votes
0   2004         ALABAMA     REPUBLICAN             0.624607
1   2004          ALASKA     REPUBLICAN             0.610653
2   2004         ARIZONA     REPUBLICAN             0.548694
3   2004        ARKANSAS     REPUBLICAN             0.543060
4   2004      CALIFORNIA       DEMOCRAT             0.543056
5   2004        COLORADO     REPUBLICAN             0.517111
6   2004     CONNECTICUT       DEMOCRAT             0.543137
7   2004        DELAWARE       DEMOCRAT             0.533468
8   2004         FLORIDA     REPUBLICAN             0.520975
9   2004         GEORGIA     REPUBLICAN             0.579748
10  2004          HAWAII       DEMOCRAT             0.540096
11  2004           IDAHO     REPUBLICAN             0.683909
12  2004        ILLINOIS       DEMOCRAT             0.548232
13  2004         INDIANA     REPUBLICAN             0.599448
14  2004            IOWA     REPUBLICAN             0.499007
15  2004          KANSAS     REPUBLICAN             0.620040
16  2004        KENTUCKY     REPUBLICAN             0.595495
17  2004       LOUISIANA     REPUBLICAN             0.567220
18  2004           MAINE       DEMOCRAT             0.535729
19  2004        MARYLAND       DEMOCRAT             0.559715
20  2004   MASSACHUSETTS       DEMOCRAT             0.616167
21  2004        MICHIGAN       DEMOCRAT             0.512307
22  2004       MINNESOTA     REPUBLICAN             0.476135
23  2004     MISSISSIPPI     REPUBLICAN             0.590144
24  2004        MISSOURI     REPUBLICAN             0.532962
25  2004         MONTANA     REPUBLICAN             0.590681
26  2004        NEBRASKA     REPUBLICAN             0.658986
27  2004          NEVADA     REPUBLICAN             0.504697
28  2004   NEW HAMPSHIRE       DEMOCRAT             0.502016
29  2004      NEW JERSEY       DEMOCRAT             0.529234
30  2004      NEW MEXICO     REPUBLICAN             0.498384
31  2004        NEW YORK       DEMOCRAT             0.561306
32  2004  NORTH CAROLINA     REPUBLICAN             0.560172
33  2004    NORTH DAKOTA     REPUBLICAN             0.628613
34  2004            OHIO     REPUBLICAN             0.508140
35  2004        OKLAHOMA     REPUBLICAN             0.655704
36  2004          OREGON       DEMOCRAT             0.513487
37  2004    PENNSYLVANIA       DEMOCRAT             0.509238
38  2004    RHODE ISLAND       DEMOCRAT             0.594234
39  2004  SOUTH CAROLINA     REPUBLICAN             0.579819
40  2004    SOUTH DAKOTA     REPUBLICAN             0.599111
41  2004       TENNESSEE     REPUBLICAN             0.567991
42  2004           TEXAS     REPUBLICAN             0.610858
43  2004            UTAH     REPUBLICAN             0.715359
44  2004         VERMONT       DEMOCRAT             0.589375
45  2004        VIRGINIA     REPUBLICAN             0.537320
46  2004      WASHINGTON       DEMOCRAT             0.528211
47  2004   WEST VIRGINIA     REPUBLICAN             0.560707
48  2004       WISCONSIN       DEMOCRAT             0.496997
49  2004         WYOMING     REPUBLICAN             0.687396

In [17]:
df_2008_election_winners

    year           state party_detailed  percent_total_votes
50  2008         ALABAMA     REPUBLICAN             0.603169
51  2008          ALASKA     REPUBLICAN             0.594245
52  2008         ARIZONA     REPUBLICAN             0.536352
53  2008        ARKANSAS     REPUBLICAN             0.587159
54  2008      CALIFORNIA       DEMOCRAT             0.610126
55  2008        COLORADO       DEMOCRAT             0.536602
56  2008     CONNECTICUT       DEMOCRAT             0.605888
57  2008        DELAWARE       DEMOCRAT             0.619427
58  2008         FLORIDA       DEMOCRAT             0.510333
59  2008         GEORGIA     REPUBLICAN             0.522045
60  2008          HAWAII       DEMOCRAT             0.714529
61  2008           IDAHO     REPUBLICAN             0.615171
62  2008        ILLINOIS       DEMOCRAT             0.619181
63  2008         INDIANA       DEMOCRAT             0.499459
64  2008            IOWA       DEMOCRAT             0.539280
65  2008          KANSAS     REPUBLICAN             0.566123
66  2008        KENTUCKY     REPUBLICAN             0.573990
67  2008       LOUISIANA     REPUBLICAN             0.585627
68  2008           MAINE       DEMOCRAT             0.577057
69  2008        MARYLAND       DEMOCRAT             0.619193
70  2008   MASSACHUSETTS       DEMOCRAT             0.613632
71  2008        MICHIGAN       DEMOCRAT             0.574332
72  2008       MINNESOTA       DEMOCRAT             0.540603
73  2008     MISSISSIPPI     REPUBLICAN             0.561762
74  2008        MISSOURI     REPUBLICAN             0.494261
75  2008         MONTANA     REPUBLICAN             0.495325
76  2008        NEBRASKA     REPUBLICAN             0.565319
77  2008          NEVADA       DEMOCRAT             0.551467
78  2008   NEW HAMPSHIRE       DEMOCRAT             0.541269
79  2008      NEW JERSEY       DEMOCRAT             0.572721
80  2008      NEW MEXICO       DEMOCRAT             0.569075
81  2008        NEW YORK       DEMOCRAT             0.601570
82  2008  NORTH CAROLINA       DEMOCRAT             0.497037
83  2008    NORTH DAKOTA     REPUBLICAN             0.532501
84  2008            OHIO       DEMOCRAT             0.515043
85  2008        OKLAHOMA     REPUBLICAN             0.656451
86  2008          OREGON       DEMOCRAT             0.567488
87  2008    PENNSYLVANIA       DEMOCRAT             0.544855
88  2008    RHODE ISLAND       DEMOCRAT             0.628640
89  2008  SOUTH CAROLINA     REPUBLICAN             0.538736
90  2008    SOUTH DAKOTA     REPUBLICAN             0.531590
91  2008       TENNESSEE     REPUBLICAN             0.568970
92  2008           TEXAS     REPUBLICAN             0.554524
93  2008            UTAH     REPUBLICAN             0.625839
94  2008         VERMONT       DEMOCRAT             0.674557
95  2008        VIRGINIA       DEMOCRAT             0.526295
96  2008      WASHINGTON       DEMOCRAT             0.576529
97  2008   WEST VIRGINIA     REPUBLICAN             0.557103
98  2008       WISCONSIN       DEMOCRAT             0.562178
99  2008         WYOMING     REPUBLICAN             0.647138

In [18]:
df_2012_election_winners

     year           state party_detailed  percent_total_votes
100  2012         ALABAMA     REPUBLICAN             0.605458
101  2012          ALASKA     REPUBLICAN             0.548016
102  2012         ARIZONA     REPUBLICAN             0.536545
103  2012        ARKANSAS     REPUBLICAN             0.605669
104  2012      CALIFORNIA       DEMOCRAT             0.602390
105  2012        COLORADO       DEMOCRAT             0.514922
106  2012     CONNECTICUT       DEMOCRAT             0.580850
107  2012        DELAWARE       DEMOCRAT             0.586107
108  2012         FLORIDA       DEMOCRAT             0.500079
109  2012         GEORGIA     REPUBLICAN             0.533292
110  2012          HAWAII       DEMOCRAT             0.701479
111  2012           IDAHO     REPUBLICAN             0.645298
112  2012        ILLINOIS       DEMOCRAT             0.576021
113  2012         INDIANA     REPUBLICAN             0.541255
114  2012            IOWA       DEMOCRAT             0.519880
115  2012          KANSAS     REPUBLICAN             0.597113
116  2012        KENTUCKY     REPUBLICAN             0.604931
117  2012       LOUISIANA     REPUBLICAN             0.577846
118  2012           MAINE       DEMOCRAT             0.553710
119  2012        MARYLAND       DEMOCRAT             0.619742
120  2012   MASSACHUSETTS       DEMOCRAT             0.603383
121  2012        MICHIGAN       DEMOCRAT             0.542082
122  2012       MINNESOTA     REPUBLICAN             0.449582
123  2012     MISSISSIPPI     REPUBLICAN             0.552858
124  2012        MISSOURI     REPUBLICAN             0.537637
125  2012         MONTANA     REPUBLICAN             0.553515
126  2012        NEBRASKA     REPUBLICAN             0.598032
127  2012          NEVADA       DEMOCRAT             0.523562
128  2012   NEW HAMPSHIRE       DEMOCRAT             0.519797
129  2012      NEW JERSEY       DEMOCRAT             0.583424
130  2012      NEW MEXICO       DEMOCRAT             0.529928
131  2012        NEW YORK       DEMOCRAT             0.607610
132  2012  NORTH CAROLINA     REPUBLICAN             0.503931
133  2012    NORTH DAKOTA     REPUBLICAN             0.583157
134  2012            OHIO       DEMOCRAT             0.506667
135  2012        OKLAHOMA     REPUBLICAN             0.667723
136  2012          OREGON       DEMOCRAT             0.542393
137  2012    PENNSYLVANIA       DEMOCRAT             0.520769
138  2012    RHODE ISLAND       DEMOCRAT             0.627010
139  2012  SOUTH CAROLINA     REPUBLICAN             0.545611
140  2012    SOUTH DAKOTA     REPUBLICAN             0.578893
141  2012       TENNESSEE     REPUBLICAN             0.594787
142  2012           TEXAS     REPUBLICAN             0.571670
143  2012            UTAH     REPUBLICAN             0.727905
144  2012         VERMONT       DEMOCRAT             0.665706
145  2012        VIRGINIA       DEMOCRAT             0.511565
146  2012      WASHINGTON       DEMOCRAT             0.561634
147  2012   WEST VIRGINIA     REPUBLICAN             0.622958
148  2012       WISCONSIN       DEMOCRAT             0.527762
149  2012         WYOMING     REPUBLICAN             0.681936

In [19]:
df_2016_election_winners

     year           state party_detailed  percent_total_votes
150  2016         ALABAMA     REPUBLICAN             0.620831
151  2016          ALASKA     REPUBLICAN             0.512815
152  2016         ARIZONA     REPUBLICAN             0.486716
153  2016        ARKANSAS     REPUBLICAN             0.605741
154  2016      CALIFORNIA       DEMOCRAT             0.617264
155  2016        COLORADO       DEMOCRAT             0.481570
156  2016     CONNECTICUT       DEMOCRAT             0.545663
157  2016        DELAWARE       DEMOCRAT             0.533533
158  2016         FLORIDA     REPUBLICAN             0.490219
159  2016         GEORGIA     REPUBLICAN             0.507713
160  2016          HAWAII       DEMOCRAT             0.609808
161  2016           IDAHO     REPUBLICAN             0.592614
162  2016        ILLINOIS       DEMOCRAT             0.558254
163  2016         INDIANA     REPUBLICAN             0.569400
164  2016            IOWA     REPUBLICAN             0.511621
165  2016          KANSAS     REPUBLICAN             0.566546
166  2016        KENTUCKY     REPUBLICAN             0.625196
167  2016       LOUISIANA     REPUBLICAN             0.580887
168  2016           MAINE       DEMOCRAT             0.463452
169  2016        MARYLAND       DEMOCRAT             0.603257
170  2016   MASSACHUSETTS       DEMOCRAT             0.590501
171  2016        MICHIGAN     REPUBLICAN             0.474976
172  2016       MINNESOTA       DEMOCRAT             0.464450
173  2016     MISSISSIPPI     REPUBLICAN             0.579410
174  2016        MISSOURI     REPUBLICAN             0.567723
175  2016         MONTANA     REPUBLICAN             0.564662
176  2016        NEBRASKA     REPUBLICAN             0.587474
177  2016          NEVADA       DEMOCRAT             0.479178
178  2016   NEW HAMPSHIRE       DEMOCRAT             0.468263
179  2016      NEW JERSEY       DEMOCRAT             0.554531
180  2016      NEW MEXICO       DEMOCRAT             0.482556
181  2016        NEW YORK       DEMOCRAT             0.561361
182  2016  NORTH CAROLINA     REPUBLICAN             0.498281
183  2016    NORTH DAKOTA     REPUBLICAN             0.629556
184  2016            OHIO     REPUBLICAN             0.516877
185  2016        OKLAHOMA     REPUBLICAN             0.653229
186  2016          OREGON       DEMOCRAT             0.500719
187  2016    PENNSYLVANIA     REPUBLICAN             0.485779
188  2016    RHODE ISLAND       DEMOCRAT             0.544066
189  2016  SOUTH CAROLINA     REPUBLICAN             0.549393
190  2016    SOUTH DAKOTA     REPUBLICAN             0.615308
191  2016       TENNESSEE     REPUBLICAN             0.607220
192  2016           TEXAS     REPUBLICAN             0.522347
193  2016            UTAH     REPUBLICAN             0.455408
194  2016         VERMONT       DEMOCRAT             0.557227
195  2016        VIRGINIA       DEMOCRAT             0.497514
196  2016      WASHINGTON       DEMOCRAT             0.525387
197  2016   WEST VIRGINIA     REPUBLICAN             0.686306
198  2016       WISCONSIN     REPUBLICAN             0.472182
199  2016         WYOMING     REPUBLICAN             0.673984

In [20]:
df_2020_election_winners

     year           state party_detailed  percent_total_votes
200  2020         ALABAMA     REPUBLICAN             0.620316
201  2020          ALASKA     REPUBLICAN             0.528331
202  2020         ARIZONA       DEMOCRAT             0.493647
203  2020        ARKANSAS     REPUBLICAN             0.623957
204  2020      CALIFORNIA       DEMOCRAT             0.634839
205  2020        COLORADO       DEMOCRAT             0.550111
206  2020     CONNECTICUT       DEMOCRAT             0.592607
207  2020        DELAWARE       DEMOCRAT             0.587430
208  2020         FLORIDA     REPUBLICAN             0.512198
209  2020         GEORGIA       DEMOCRAT             0.494731
210  2020          HAWAII       DEMOCRAT             0.631494
211  2020           IDAHO     REPUBLICAN             0.638376
212  2020        ILLINOIS       DEMOCRAT             0.575416
213  2020         INDIANA     REPUBLICAN             0.570212
214  2020            IOWA     REPUBLICAN             0.528002
215  2020          KANSAS     REPUBLICAN             0.562125
216  2020        KENTUCKY     REPUBLICAN             0.620866
217  2020       LOUISIANA     REPUBLICAN             0.584609
218  2020           MAINE       DEMOCRAT             0.525256
219  2020        MARYLAND       DEMOCRAT             0.653607
220  2020   MASSACHUSETTS       DEMOCRAT             0.651230
221  2020        MICHIGAN       DEMOCRAT             0.506208
222  2020       MINNESOTA       DEMOCRAT             0.523951
223  2020     MISSISSIPPI     REPUBLICAN             0.576030
224  2020        MISSOURI     REPUBLICAN             0.567997
225  2020         MONTANA     REPUBLICAN             0.569185
226  2020        NEBRASKA     REPUBLICAN             0.582242
227  2020          NEVADA       DEMOCRAT             0.500568
228  2020   NEW HAMPSHIRE       DEMOCRAT             0.527078
229  2020      NEW JERSEY       DEMOCRAT             0.573342
230  2020      NEW MEXICO       DEMOCRAT             0.542893
231  2020        NEW YORK       DEMOCRAT             0.603919
232  2020  NORTH CAROLINA     REPUBLICAN             0.499343
233  2020    NORTH DAKOTA     REPUBLICAN             0.651140
234  2020            OHIO     REPUBLICAN             0.532713
235  2020        OKLAHOMA     REPUBLICAN             0.653733
236  2020          OREGON       DEMOCRAT             0.564533
237  2020    PENNSYLVANIA       DEMOCRAT             0.500085
238  2020    RHODE ISLAND       DEMOCRAT             0.594762
239  2020  SOUTH CAROLINA     REPUBLICAN             0.550935
240  2020    SOUTH DAKOTA     REPUBLICAN             0.617694
241  2020       TENNESSEE     REPUBLICAN             0.606603
242  2020           TEXAS     REPUBLICAN             0.520576
243  2020            UTAH     REPUBLICAN             0.581298
244  2020         VERMONT       DEMOCRAT             0.654558
245  2020        VIRGINIA       DEMOCRAT             0.541095
246  2020      WASHINGTON       DEMOCRAT             0.579703
247  2020   WEST VIRGINIA     REPUBLICAN             0.686316
248  2020       WISCONSIN       DEMOCRAT             0.494495
249  2020         WYOMING     REPUBLICAN             0.694998

Export as csvs

In [ ]:
df_2004_election_winners.to_csv('pres-election-results-2004.csv')
df_2008_election_winners.to_csv('pres-election-results-2008.csv')
df_2012_election_winners.to_csv('pres-election-results-2012.csv')
df_2016_election_winners.to_csv('pres-election-results-2016.csv')
df_2020_election_winners.to_csv('pres-election-results-2020.csv')